language: rust
dist: bionic
rust:
  - 1.41.1
cache: cargo
addons:
    postgresql: "12"
    apt:
        packages:
            - postgresql-12
jobs:
  include:
    - stage: "tests"
      name: "Running the tests"
      script:
          - cargo test
    - stage: "prod"
      name: "Production build"
      script: cargo build --release
      if: branch = master
