language: rust
dist: bionic
rust:
  - stable
cache: cargo
jobs:
  include:
    - stage: "syntax"
      name: "Checking syntax"
      script: cargo check
    - stage: "tests"
      name: "Running the tests"
      script: cargo test
    - stage: "prod"
      name: "Production build"
      script: cargo build --release
