language: rust
os: linux
rust:
  - 1.41.1
cache: cargo

env:
    - RUST_BACKTRACE=1

services:
    - postgresql

before_script:
  - psql -c 'create database build_db;' -U postgres
  - echo "DATABASE_URL=postgres://postgres@localhost/build_db" > .env
  - if which diesel; then echo "diesel already installed"; else cargo install diesel_cli --no-default-features --features=postgres; fi
  - diesel migration run


script:
    - cargo test
