language: rust
os: linux
rust:
  - 1.41.1
cache: cargo

env:
    global:
        - RUST_BACKTRACE=1
        - PGPORT: 5433

services:
    - postgresql
addons:
    postgresql: "12"
    apt:
        packages:
            - postgresql-12
            - postgresql-client-12

before_script:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - psql -c 'create database build_db;' -U postgres
  - echo "DATABASE_URL=postgres://postgres@localhost/build_db" > .env
  - if which diesel; then echo "diesel already installed"; else cargo install diesel_cli --no-default-features --features=postgres; fi
  - diesel migration run


script:
    - cargo test
